server:
  http:
    address: 0.0.0.0:8001
    timeout: 1s
  grpc:
    address: 0.0.0.0:9001
    timeout: 1s
  auth:
    adminToken: "63a16b29e5bc4a28a880de1b2e707cc6"
    guestToken: "863676f1118c45c7add65b4adefd94dd"
data:
  database:
    driver: postgres
    source: host=localhost port=5432 user=postgres password=123 dbname=kratos_examples_db sslmode=disable
